# Generated by Django 4.2.7 on 2024-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Register_Login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="DOB",
            field=models.TimeField(),
        ),
    ]
