# Generated by Django 4.2.7 on 2024-10-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Register_Login", "0002_alter_profile_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="DOB",
        ),
    ]
