# Generated by Django 5.1.2 on 2024-10-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_remove_profile_created_profile_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='img',
        ),
    ]
