# Generated by Django 5.1.2 on 2024-10-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0005_rename_image_volunteer_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivityCategory',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
