# Generated by Django 5.1.2 on 2024-10-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_article_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.category'),
        ),
    ]
