# Generated by Django 5.1.2 on 2024-10-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_rename_created_article_publish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
