# Generated by Django 5.1.2 on 2024-10-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_feedback_email_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=160),
        ),
    ]
