# Generated by Django 5.1.2 on 2024-10-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='visited_times',
        ),
    ]
