# Generated by Django 5.1.2 on 2024-10-25 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0005_alter_blacklistip_id_alter_blacklistuseragent_id_and_more'),
        ('telegram', '0012_delete_userhit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.CreateModel(
            name='UserHitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitcount.hitcount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserActivityCategory',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
