# Generated by Django 5.1.2 on 2024-10-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0013_remove_useractivity_activity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHitCount',
        ),
    ]
