# Generated by Django 5.1.2 on 2024-10-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0015_userhit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhit',
            name='hit',
        ),
    ]
