# Generated by Django 5.1.2 on 2024-10-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0005_alter_blacklistip_id_alter_blacklistuseragent_id_and_more'),
        ('telegram', '0016_remove_userhit_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhit',
            name='hit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hitcount.hitcount'),
        ),
    ]
