# Generated by Django 5.1.2 on 2024-10-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0017_userhit_hit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHit',
        ),
    ]
