# Generated by Django 5.1.2 on 2024-10-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_remove_article_uploaded_at_subcategory_main_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_category',
            new_name='Main_Category',
        ),
    ]
