# Generated by Django 5.1.2 on 2024-10-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_rename_main_category_subcategory_main_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='img',
        ),
    ]
