# Generated by Django 5.1.2 on 2024-10-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_userhit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHit',
        ),
    ]
